@startuml

autonumber
title Update Quotes and Images Sequence Diagram

participant "Stocks Service" as StocksService
box "Firebase"
    participant getSymbols <<Function>>
    participant updateImages <<Function>>
    participant updateQuotes <<Function>>
    database "Cloud Firestore" as CloudFirestore <<Database>>
    participant "Images Bucket" as ImagesBucket <<Storage>>
end box
participant "IEX API" as IexApi

loop per minute
    StocksService -> getSymbols: get symbols
    getSymbols -> CloudFirestore: get symbols
    CloudFirestore --> getSymbols: return symbols
    getSymbols --> StocksService: return symbols
    alt new symbols or 5 min passed
        StocksService -> IexApi: get quotes
        note right
            GET /stock/{symbol}/quote
        end note
        IexApi --> StocksService: return quotes
        StocksService -> updateQuotes: push quotes
        updateQuotes -> CloudFirestore: update quotes
        note right
            /quotes/{symbol}
        end note
    end
    alt new symbols or 1 week passed
        StocksService -> IexApi: get logos
        note right
            GET /stock/{symbol}/logo
        end note
        IexApi --> StocksService: return logos
        StocksService -> updateImages: push logos images
        updateImages -> ImagesBucket: update logos images
        note right
            /logos/{symbol}
        end note
        ImagesBucket --> updateImages: return logos images URLs
        updateImages -> CloudFirestore: update logos images URLs
        note right
            /logos/{symbol}
        end note
    end
end

@enduml
