@startuml

title Solution Architecture Diagram

actor User

cloud Firebase {
    package Authentication {
        component "Google Authentication" as GoogleAuth
    }

    package Database {
        database "Cloud Firestore" as CloudFirestore
    }

    package Functions {
        component getSymbols
        component updateImages
        component updateQuotes
    }

    package Hosting {
        component Portfolio
    }

    package Storage {
        storage "Images Bucket" as ImagesBucket
    }
}

cloud "TODO" {
    component "Stocks Service" as StocksService
}

cloud "IEX Cloud" {
    component "IEX API" as IexApi
}

User ..> Portfolio
User ..> GoogleAuth

Portfolio --> GoogleAuth : INT01
Portfolio --> CloudFirestore : INT02
Portfolio --> ImagesBucket : INT03

StocksService --> getSymbols : INT04
StocksService --> IexApi : INT05
StocksService --> updateQuotes : INT06
StocksService --> updateImages : INT07

getSymbols --> CloudFirestore : INT08

updateQuotes --> CloudFirestore : INT09

updateImages --> ImagesBucket : INT10
updateImages --> CloudFirestore : INT11

@enduml
