@startuml

actor User

cloud Firebase {
    package Authentication {
        component "Google\nAuthentication" as GoogleAuth
    }

    package Database {
        database "Cloud\nFirestore" as CloudFirestore
    }

    package Functions {
        component getSymbols
        component updateImages
        component updateQuotes
    }

    package Hosting {
        component Portfolio
    }

    package Storage {
        storage "Images\nBucket" as ImagesBucket
    }
}

cloud "?" {
    component "Quotes\nService" as QuotesService
}

cloud "IEX Cloud" {
    component "IEX API" as IexApi
}

User ..> Portfolio
User ..> GoogleAuth

Portfolio --> GoogleAuth : INT01
Portfolio --> CloudFirestore : INT02
Portfolio --> ImagesBucket : INT03

QuotesService --> getSymbols : INT04
QuotesService --> IexApi : INT05
QuotesService --> updateQuotes : INT06
QuotesService --> updateImages : INT07

getSymbols --> CloudFirestore : INT08

updateQuotes --> CloudFirestore : INT09

updateImages --> ImagesBucket : INT10
updateImages --> CloudFirestore : INT11

@enduml
