/* @flow */

export const AUTHORIZATION_TOKEN_SET = 'AUTHORIZATION_TOKEN_SET';
export const BROKERAGE_ACCOUNT_SET = 'BROKERAGE_ACCOUNT_SET';
export const DIFF_RECEIVED = 'DIFF_RECEIVED';
export const DIFF_REQUESTED = 'DIFF_REQUESTED';
export const LOGGED_OUT = 'LOGGED_OUT';
export const STOCK_ADDED = 'STOCK_ADDED';
export const STOCK_PRICE_RECEIVED = 'STOCK_PRICE_RECEIVED';
export const STOCK_PRICE_REQUESTED = 'STOCK_PRICE_REQUESTED';
export const STOCK_REMOVED = 'STOCK_REMOVED';
export const TOKENS_RECEIVED = 'TOKENS_RECEIVED';
export const TOKENS_REQUESTED = 'TOKENS_REQUESTED';
