@startuml

object Firestore <<Document>> {
    assets: AssetsCollection
    users: UsersCollection
    usersPortfolios: UsersPortfoliosCollection
}

object AssetsCollection <<Collection>> {
    [assetId]: AssetDocument
}

object AssetDocument <<Document>> {
    price: number
    title: string
    type: string
}

object UsersCollection <<Collection>> {
    [userId]: UserDocument
}

object UserDocument <<Document>> {
    avatarUrl: string
    displayName: string
    email: string
}

object UsersPortfoliosCollection <<Collection>> {
    [userId]: UserPortfoliosDocument
}

object UserPortfoliosDocument <<Document>> {
    portfolios: PortfoliosCollection
}

object PortfoliosCollection <<Collection>> {
    [portfolioId]: PortfolioDocument
}

object PortfolioDocument <<Document>> {
    openPositions: OpenPositionsCollection
    closedPositions: ClosedPositionsCollection
    title: string
}

object OpenPositionsCollection <<Collection>> {
    [positionId]: OpenPositionDocument
}

object OpenPositionDocument <<Document>> {
    TODO
    yields: YieldsCollection
}

object ClosedPositionsCollection <<Collection>> {
    [positionId]: ClosedPositionDocument
}

object ClosedPositionDocument <<Document>> {
    TODO
    yields: YieldsCollection
}

object YieldsCollection <<Collection>> {
    [yield]: YieldDocument
}

object YieldDocument <<Document>> {
    TODO
}

object UsersForecastsCollection <<Collection>> {
    [userId]: UserForecastsDocument
}

object UserForecastsDocument <<Document>> {
    forecasts: ForecastsCollection
}

object ForecastsCollection <<Collection>> {
    [forecastId]: ForecastDocument
}

object ForecastDocument <<Document>> {
    assetId: string
    price: number
}

Firestore --> AssetsCollection
AssetsCollection --> AssetDocument

Firestore --> UsersCollection
UsersCollection --> UserDocument

Firestore --> UsersPortfoliosCollection
UsersPortfoliosCollection --> UserPortfoliosDocument
UserPortfoliosDocument --> PortfoliosCollection
PortfoliosCollection --> PortfolioDocument
PortfolioDocument --> OpenPositionsCollection
OpenPositionsCollection --> OpenPositionDocument
PortfolioDocument --> ClosedPositionsCollection
ClosedPositionsCollection --> ClosedPositionDocument
OpenPositionDocument --> YieldsCollection
ClosedPositionDocument --> YieldsCollection
YieldsCollection --> YieldDocument

Firestore --> UsersForecastsCollection
UsersForecastsCollection --> UserForecastsDocument
UserForecastsDocument --> ForecastsCollection
ForecastsCollection --> ForecastDocument

@enduml
