@startuml

object Firestore <<Document>> {
    assets: AssetsCollection
    users: UsersCollection
    usersPortfolios: UsersPortfoliosCollection
}

object AssetsCollection <<Collection>> {
    [assetId]: AssetDocument
}

object AssetDocument <<Document>> {
    externalId: string
    type: AssetType
    ..
    price: number
    title: string
    financialsUpdatedAt: timestamp
    ..
    logoUrl: string
    logoUpdatedAt: timestamp
    ..
    paletteUrl: string
    paletteUpdatedAt: timestamp
}

object UsersCollection <<Collection>> {
    [userId]: UserDocument
}

object UserDocument <<Document>> {
    avatarUrl: string
    displayName: string
    email: string
    ...
}

object UsersPortfoliosCollection <<Collection>> {
    [userId]: UserPortfoliosDocument
}

object UserPortfoliosDocument <<Document>> {
    portfolios: PortfoliosCollection
}

object PortfoliosCollection <<Collection>> {
    [portfolioId]: PortfolioDocument
}

object PortfolioDocument <<Document>> {
    openPositions: OpenPositionsCollection
    closedPositions: ClosedPositionsCollection
    --
    title: string
}

object OpenPositionsCollection <<Collection>> {
    [positionId]: OpenPositionDocument
}

object OpenPositionDocument <<Document>> {
    yields: YieldsCollection
    --
    assetId: string
    amount: number
    ..
    openDate: timestamp
    openPrice: number
    openCommission: number
}

object ClosedPositionsCollection <<Collection>> {
    [positionId]: ClosedPositionDocument
}

object ClosedPositionDocument <<Document>> {
    yields: YieldsCollection
    --
    assetId: string
    amount: number
    ..
    openDate: timestamp
    openPrice: number
    openCommission: number
    ..
    closedDate: timestamp
    closedPrice: number
    closedCommission: number
}

object YieldsCollection <<Collection>> #lightgray {
    [yieldId]: YieldDocument
}

object YieldDocument <<Document>> #lightgray {
    date: timestamp
    sum: number
    commission: number
}

object UsersForecastsCollection <<Collection>> #lightgray {
    [userId]: UserForecastsDocument
}

object UserForecastsDocument <<Document>> #lightgray {
    forecasts: ForecastsCollection
}

object ForecastsCollection <<Collection>> #lightgray {
    [forecastId]: ForecastDocument
}

object ForecastDocument <<Document>> #lightgray {
    assetId: string
    price: number
}

Firestore --> AssetsCollection
AssetsCollection --> AssetDocument

Firestore --> UsersCollection
UsersCollection --> UserDocument

Firestore --> UsersPortfoliosCollection
UsersPortfoliosCollection --> UserPortfoliosDocument
UserPortfoliosDocument --> PortfoliosCollection
PortfoliosCollection --> PortfolioDocument
PortfolioDocument --> OpenPositionsCollection
OpenPositionsCollection --> OpenPositionDocument
PortfolioDocument --> ClosedPositionsCollection
ClosedPositionsCollection --> ClosedPositionDocument
OpenPositionDocument --> YieldsCollection
ClosedPositionDocument --> YieldsCollection
YieldsCollection --> YieldDocument

Firestore --> UsersForecastsCollection
UsersForecastsCollection --> UserForecastsDocument
UserForecastsDocument --> ForecastsCollection
ForecastsCollection --> ForecastDocument

@enduml
