@startuml

autonumber

actor User
box Firebase
    participant "Web App" as WebApp <<Hosting>>
    database Database <<Firestore>>
    participant "Create Asset" as CreateAsset <<Function>>
end box
participant "External Service" as ExternalService <<Asset Provider>>

User -> WebApp: open new position
alt asset ID unavailable
    WebApp -> CreateAsset: post asset external ID and type
    note right
        POST /createAsset
    end note
    CreateAsset -> Database: query assets with requested\nexternal ID and type
    alt
        Database --> CreateAsset: return assets collection
        CreateAsset --> WebApp: return first asset ID
        note right
            HTTP 303 See Other
        end note
    else
        Database --> CreateAsset: return empty collection
        CreateAsset -> CreateAsset: pick asset provider\nbased on asset type
        CreateAsset -> ExternalService: get asset financials by external ID
        ExternalService --> CreateAsset: return asset financials
        CreateAsset -> Database: store asset
        Database --> CreateAsset: return asset ID
        CreateAsset --> WebApp: return asset ID
        note right
            HTTP 201 Created
        end note
    end
end
WebApp -> Database: store new position
Database --> WebApp: update positions
WebApp --> User: show new position

@enduml
