@startuml

autonumber
title Open Position Sequence Diagram

actor User
box Firebase
    participant Portfolio <<Hosting>>
    database "Cloud Firestore" as CloudFirestore <<Database>>
end box

User -> Portfolio: open new position
Portfolio -> CloudFirestore: publish new position data
CloudFirestore -> Portfolio: update positions list
Portfolio --> User: show new position screen
note right
    If stock symbol is not present
    in the database, its image and
    quote appear within 1 minute
end note

@enduml
