@startuml

autonumber

box Firebase
    participant "Rates Storage" as RatesStorage <<Storage>>
    participant "Update Rates" as UpdateRates <<Function>>
end box
participant "Rates Provider" as RatesProvider

loop twice per day
    UpdateRates -> RatesProvider: get rates
    RatesProvider --> UpdateRates: return rates
    UpdateRates -> RatesStorage: store rates file
end

@enduml
