@startuml

autonumber

box Firebase
    database Database <<Firestore>>
    participant "Logos Storage" as LogosStorage <<Storage>>
    participant "Update Assets Logos" as UpdateAssetsLogos <<Function>>
end box
participant "External Service" as ExternalService <<Asset Provider>>

loop per day
    UpdateAssetsLogos -> Database: query assets with expired logos
    Database --> UpdateAssetsLogos: return assets collection
    loop per asset
        UpdateAssetsLogos -> UpdateAssetsLogos: pick asset provider\nbased on asset type
        UpdateAssetsLogos -> ExternalService: get asset logo by external ID
        ExternalService --> UpdateAssetsLogos: return asset logo
    end
    loop per asset
        UpdateAssetsLogos -> LogosStorage: store asset logo
        LogosStorage --> UpdateAssetsLogos: return asset logo URL
    end
    UpdateAssetsLogos -> Database: update assets logos
end

@enduml
