@startuml

autonumber

box Firebase
    participant "Rates Bucket" as RatesBucket <<Bucket>>
    participant "Update Rates" as UpdateRates <<Function>>
end box
participant "Rates Provider" as RatesProvider

loop twice per day
    UpdateRates -> RatesProvider: get rates
    RatesProvider --> UpdateRates: return rates
    UpdateRates -> RatesBucket: store rates file
end

@enduml
